package io.openmarket.order.model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

import static io.openmarket.config.OrderConfig.*;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = ORDER_DDB_TABLE_NAME)
public class Order {
    @DynamoDBHashKey
    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_ORDER_ID)
    private String orderId;

    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_BUYER_ID)
    private String buyerId;

    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_SELLER_ID)
    private String sellerId;

    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_CURRENCY)
    private String currency;

    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_TOTAL_AMOUNT)
    private double total;

    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_TRANSACTION_ID)
    private String transactionId;

    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_STATUS)
    @DynamoDBTypeConvertedEnum
    private OrderStatus status;

    @DynamoDBTypeConverted(converter = ItemInfoConverter.class)
    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_ITEMS)
    private List<ItemInfo> items;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBTypeConvertedTimestamp
    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_UPDATED_AT)
    private String lastUpdatedAt;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBTypeConvertedTimestamp
    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_CREATED_AT)
    private String createdAt;
}