package io.openmarket.order.model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

import static io.openmarket.config.OrderConfig.*;


@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = ORDER_DDB_TABLE_NAME)
public class Order {


    @DynamoDBHashKey
    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_ID)
    private String orderId;

    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_BUYER)
    private String buyer;

    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_SELLER)
    private String seller;

    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_DELIVERY_METHOD)
    private String delivery_method;

    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_TRACKING_NUMBER)
    private String tracking_number;

    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_PAYMENT_METHOD)
    private String payment_method;

    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_DELIVERY_ADDR)
    private String delivery_address;

    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_TOTAL)
    private double total;

    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_ITEM_SUMMARY)
    private List<ItemInfo> item_summary;

    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_TRANSACTION_ID)
    private String transactionId;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBTypeConvertedTimestamp
    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_UPDATED_AT)
    private String lastUpdatedAt;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBTypeConvertedTimestamp
    @DynamoDBAttribute(attributeName = ORDER_DDB_ATTRIBUTE_CREATED_AT)
    private String createdAt;
}