package io.openmarket.transaction.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.util.Date;
import java.util.List;

import static io.openmarket.config.TransactionConfig.*;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = TRANSACTION_DDB_TABLE_NAME)
public class Transaction {
    @DynamoDBHashKey(attributeName = TRANSACTION_DDB_ATTRIBUTE_ID)
    @DynamoDBAutoGeneratedKey
    @NonNull private String transactionId;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = TRANSACTION_DDB_ATTRIBUTE_TYPE)
    @NonNull private TransactionType type;

    @DynamoDBAttribute(attributeName = TRANSACTION_DDB_ATTRIBUTE_PAYER_ID)
    @NonNull private String payerId;

    @DynamoDBAttribute(attributeName = TRANSACTION_DDB_ATTRIBUTE_RECIPIENT_ID)
    @NonNull private String recipientId;

    @DynamoDBAttribute(attributeName = TRANSACTION_DDB_ATTRIBUTE_CURRENCY_ID)
    @NonNull private String currencyId;

    @DynamoDBAttribute(attributeName = TRANSACTION_DDB_ATTRIBUTE_AMOUNT)
    @NonNull private Double amount;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = TRANSACTION_DDB_ATTRIBUTE_STATUS)
    @NonNull private TransactionStatus status;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = TRANSACTION_DDB_ATTRIBUTE_ERROR_STATUS)
    private TransactionErrorType error;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBTypeConvertedTimestamp
    @DynamoDBAttribute(attributeName = TRANSACTION_DDB_ATTRIBUTE_CREATED_AT)
    private Date createdAt;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBTypeConvertedTimestamp
    @DynamoDBAttribute(attributeName = TRANSACTION_DDB_ATTRIBUTE_UPDATED_AT)
    private Date lastUpdatedAt;

    @DynamoDBAttribute(attributeName = TRANSACTION_DDB_ATTRIBUTE_NOTE)
    private String note;

    @DynamoDBAttribute(attributeName = TRANSACTION_DDB_ATTRIBUTE_REFUND_TRANSAC_ID)
    private List<String> refundTransacIds;

    @DynamoDBVersionAttribute
    private Integer version;
}
